name: interpret-compression
channels:
- conda-forge
- bioconda
dependencies:
- conda-forge::python=3.6
- conda-forge::pandas=0.23.4
- conda-forge::xlrd=1.1.0
- conda-forge::numpy=1.15.2
- conda-forge::seaborn=0.8.1
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=4.8.1
- conda-forge::nb_conda_kernels=2.1.0
- conda-forge::openpyxl=2.5.1
- conda-forge::r-dplyr=0.7.4
- conda-forge::r-tidyr=0.8.0
- conda-forge::r-readr=1.1.1
- conda-forge::r-readxl=1.1.0
- conda-forge::r-ggplot2=2.2.1
- conda-forge::r-irkernel=0.8.11
- bioconda::gseapy=0.9.5
- pip:
  - git+https://github.com/dhimmel/hetio@9d9ef1320ee47609e3c61c9f4918531d3c1c8c96
  - git+https://github.com/greenelab/tybalt@739cfb894426b2dcedcf3ed48e3a43733a5cac2e
  - git+https://github.com/greenelab/hetmech@b4aca774a2e9b41e6c448535d3b1cc2d9b3f85f4
