name: interpret-compression
channels:
- conda-forge
dependencies:
- conda-forge::python=3.6
- conda-forge::pandas=0.22.0
- conda-forge::xlrd=1.1.0
- conda-forge::numpy=1.14.2
- conda-forge::seaborn=0.8.1
- conda-forge::jupyter=1.0.0
- conda-forge::ipykernel=4.8.1
- conda-forge::nb_conda_kernels=2.1.0
- conda-forge::openpyxl=2.5.1
- conda-forge::r-dplyr=0.7.4
- conda-forge::r-tidyr=0.8.0
- conda-forge::r-readr=1.1.1
- conda-forge::r-ggplot2=2.2.1
- conda-forge::r-irkernel=0.8.11
- pip:
  - git+https://github.com/dhimmel/hetio@9d9ef1320ee47609e3c61c9f4918531d3c1c8c96
  - git+https://github.com/greenelab/tybalt@1af6086a1f4bfee035b4d25789cdb1d53361fefc
  - git+https://github.com/greenelab/hetmech@3caf7791b32f0104cdfe362eab884d9f97a8cb1a
